### ISSUE TITLE
BEACON directory deleted upon git clone

### ISSUE THREAD

**Issue by victorskl** [EGA-archive/beacon2-ri-tools#13]
Dear @mrueda 

It looks like whenever I try fresh git clone, I get the following message without modifying any. Would be great, if you could have a look.

```
git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    BEACON/Beacon.pm
	deleted:    BEACON/Config.pm
	deleted:    BEACON/Help.pm
	deleted:    BEACON/bin/BFF.pm
	deleted:    BEACON/bin/bff2html.pl
	deleted:    BEACON/bin/bff2json.pl
	deleted:    BEACON/bin/deploy_external_tools.sh
	deleted:    BEACON/bin/run_bff2html.sh
	deleted:    BEACON/bin/run_bff2mongodb.sh
	deleted:    BEACON/bin/run_vcf2bff.sh
	deleted:    BEACON/bin/vcf2bff.pl
```

**Comment by victorskl** [comment]
And. If I do:

```
git restore BEACON/
```

Then I got back `BEACON/`. However. There is git status, saying `beacon/` deletion.

```
git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    beacon

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by mrueda** [comment]
Hi Victor,

I can't replicate the error on Linux (Debian-based).

Quick question, are you using a MAC with case-insensitive filesystem? The reason I am asking is because the software expects the filesystem to be case-sensitive.

Best,

Manu

**Comment by victorskl** [comment]
> Quick question, are you using a MAC with case-insensitive filesystem? 

Yes, I'm using macOS, default file system.

> The reason I am asking is because the software expects the filesystem to be case-sensitive.

Ah right. Ok, thanks.
