### ISSUE TITLE
Can't pull docker image from docker hub 

### ISSUE THREAD

**Issue by mshadbolt** [EGA-archive/beacon2-ri-tools#7]
Hello

I tried to grab the latest docker image by following the commands in the documentation but it is giving me the following errors

```
marionfs@5000L-205837-M ~ % docker pull mmoldes/beacon_reference_implementation
Using default tag: latest
Error response from daemon: manifest for mmoldes/beacon_reference_implementation:latest not found: manifest unknown: manifest unknown
marionfs@5000L-205837-M ~ % docker pull mmoldes/beacon_reference_implementation:latest
Error response from daemon: Head "https://registry-1.docker.io/v2/mmoldes/beacon_reference_implementation/manifests/latest": EOF
```

I use Docker regularly for other things and haven't had any issues and just updated, so I don't think it is a docker issue, but let me know if there's anything I should try. I will try using outside docker but thought I would post issue in case others experience the same.

Cheers
Marion

**Comment by SergiAguilo** [comment]
Hi,

I'm using Docker version 19.03.11 and having the first error for both command lines.

Thanks for point it out!

Sergi

**Comment by mrueda** [comment]
Thanks you both for the heads up.

Please use the following command instead:
`docker pull mmoldes/beacon_reference_implementation:1.0`
