### ISSUE TITLE
Can't download data from ftp

### ISSUE THREAD

**Issue by mshadbolt** [EGA-archive/beacon2-ri-tools#8]
I attempted downloading the data files from the ftp following the instructions here for ['non-containerized version'](https://b2ri-documentation.readthedocs.io/en/latest/download-and-installation/).

When I run the ftp command it only downloads `beacon2_data.part_1` and `beacon2_data.part_2` but the documentation says there should be 5 parts. I tried to have a look around in the ftp but couldn't find anything. Is there somewhere I can download the other parts in order to use the tools?

Thanks

Marion

**Comment by mrueda** [comment]
Hello @mshadbolt, yep, something changed on our ftp site and the `wget` was not downloading the 5+1 files. 
Please, use instead:
```
wget ftp://xfer13.crg.eu:221/beacon2_data.md5
wget ftp://xfer13.crg.eu:221/beacon2_data.part1
wget ftp://xfer13.crg.eu:221/beacon2_data.part2
wget ftp://xfer13.crg.eu:221/beacon2_data.part3
wget ftp://xfer13.crg.eu:221/beacon2_data.part4
wget ftp://xfer13.crg.eu:221/beacon2_data.part5
```
Note that we also added a `Dockerfile` at the root of this repo that supposedly :cry: will simplify things.

**Comment by mshadbolt** [comment]
ok great thanks! it is now downloading (very slowly - 1 part is estimated to take 11 hours to an AWS EC2 instance in Australia...)
