### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by alin-png** [EGA-archive/beacon2-ri-tools#9]
Hi, 

I've tried to build the docker image using the Dockerfile available. However, it looks like the build fails during installation of Perl libraries:
```
...
#14 276.6 --> Working on JSON::Validator
#14 276.6 Fetching http://www.cpan.org/authors/id/J/JH/JHTHORSEN/JSON-Validator-5.08.tar.gz ... OK
#14 276.9 Configuring JSON-Validator-5.08 ... OK
#14 277.0 Building and testing JSON-Validator-5.08 ... OK
#14 295.3 Successfully installed JSON-Validator-5.08
#14 295.8 --> Working on File::Which
#14 295.8 Fetching http://www.cpan.org/authors/id/P/PL/PLICEASE/File-Which-1.27.tar.gz ... OK
#14 295.9 
#14 295.9 gzip: stdin: unexpected end of file
#14 295.9 /usr/bin/tar: Child returned status 1
#14 295.9 /usr/bin/tar: Error is not recoverable: exiting now
#14 295.9 ! Failed to unpack File-Which-1.27.tar.gz: no directory
#14 295.9 ! Failed to fetch distribution File-Which-1.27
#14 295.9 ! Installing the dependencies failed: Module 'File::Which' is not installed
#14 295.9 ! Bailing out the installation for ..
#14 295.9 33 distributions installed
------
executor failed running [/bin/sh -c cpanm --sudo --installdeps .]: exit code: 1

```
Do you have any suggestions to solve this issue? Thanks!

**Comment by mrueda** [comment]
Hi @alin-png, could you please download the `Dockerfile` again and give it a new try?

Thx,

m

**Comment by alin-png** [comment]
Hi @mrueda, thank you for uploading a new `Dockerfile`. 
Unfortunately I am still receiving this error (I had also removed the previous image on my device before running `docker build`):

```
...
--> Working on Text::CSV_XS
Fetching http://www.cpan.org/authors/id/H/HM/HMBRAND/Text-CSV_XS-1.48.tgz ... OK
Configuring Text-CSV_XS-1.48 ... OK
Building and testing Text-CSV_XS-1.48 ... OK
Successfully installed Text-CSV_XS-1.48
--> Working on File::Which
Fetching http://www.cpan.org/authors/id/P/PL/PLICEASE/File-Which-1.27.tar.gz ... OK

gzip: stdin: unexpected end of file
/usr/bin/tar: Child returned status 1
/usr/bin/tar: Error is not recoverable: exiting now
! Failed to unpack File-Which-1.27.tar.gz: no directory
! Failed to fetch distribution File-Which-1.27
--> Working on PerlIO::gzip
Fetching http://www.cpan.org/authors/id/N/NW/NWCLARK/PerlIO-gzip-0.20.tar.gz ... OK
Configuring PerlIO-gzip-0.20 ... OK
Building and testing PerlIO-gzip-0.20 ... OK
Successfully installed PerlIO-gzip-0.20
--> Working on JSON::XS
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/JSON-XS-4.03.tar.gz ... OK
==> Found dependencies: Canary::Stability
--> Working on Canary::Stability
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/Canary-Stability-2013.tar.gz ... OK
Configuring Canary-Stability-2013 ... OK
Building and testing Canary-Stability-2013 ... OK
Successfully installed Canary-Stability-2013
Configuring JSON-XS-4.03 ... OK
==> Found dependencies: common::sense, Types::Serialiser
--> Working on common::sense
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/common-sense-3.75.tar.gz ... OK
Configuring common-sense-3.75 ... OK
Building and testing common-sense-3.75 ... OK
Successfully installed common-sense-3.75
--> Working on Types::Serialiser
Fetching http://www.cpan.org/authors/id/M/ML/MLEHMANN/Types-Serialiser-1.01.tar.gz ... OK
Configuring Types-Serialiser-1.01 ... OK
Building and testing Types-Serialiser-1.01 ... OK
Successfully installed Types-Serialiser-1.01
Building and testing JSON-XS-4.03 ... OK
Successfully installed JSON-XS-4.03
! Installing the dependencies failed: Module 'File::Which' is not installed
! Bailing out the installation for ..
33 distributions installed
The command '/bin/sh -c cpanm --sudo --installdeps .' returned a non-zero code: 1
```

Fortunately I am able to pull the image from Docker Hub and that works perfectly. I will use that in the meantime. Thanks! 👍

**Comment by mrueda** [comment]
Interesting :confused: ...

I haven’t been able to reproduce the error locally (tested in Linux Mint and Ubuntu with two different LAN – home and work). 

Anyhow, since this error happened to you it’s likely that it may happen to someone else so I’d like to investigate a bit.

I suspect it has to do either with:

- A particularity of your server
- Versioning (alternative mirrors in your zone for CPAN or Ubuntu)

Ok, we're going to try installing the Perl Module `File::Which` locally (outside the container) and see what happens.

I will ask you to install two things as `sudo` (they're harmless) and then install the module in a local environment

```
sudo apt-get install cpanm 
cpanm –sudo Carton
```
Now we create a `cpanfile` with this:
```
cat<<EOF>cpanfile
requires 'File::Which';
EOF
```

And now proceed with the local env installation
`carton install `

Is the module correctly installed? Depending on this I will give you more instructions. LMK.

Thanks,

m

**Comment by alin-png** [comment]
Hi @mrueda, thanks so much for all your hard work to help me with this. It turns out it the issue was caused by being on a VPN which prevented me from fetching `http://www.cpan.org/authors/id/P/PL/PLICEASE/File-Which-1.27.tar.gz` to install the `File::Which` module... 

It's working smoothy now that I am off the VPN. Thank you and apologies for the trouble that I could have easily caught from the beginning... I'll close this issue :)
